spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/msa-study-account-book
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# jpa log settings
logging:
  level:
    org.hibernate.SQL: debug

# server settings
server:
  port: 8001
